spring:
    # config:
    #     activate:
    #         on-profile: pc
    # 此配置不生效，由maven启动参数配置

    application:
        name: poker-game-v2

    # redis
    session:
        store-type: redis
    redis:
        database: 0
        host: 127.0.0.1
        port: 6379
        jedis:
            pool:
                min-idle: 10000
        timeout: 30000

server:
    port: 8080

# log
logging:
    level:
        root: info

mybatis:
    mapper-locations: classpath:mybatis/*.xml
    type-aliases-package: com.samay.game.entity