spring:
    # config:
    #     activate:
    #         on-profile: pc
    # 此配置不生效，由maven启动参数配置

    application:
        name: poker-game-v2

server:
    port: 8080

# log
logging:
    level:
        root: info

mybatis:
    mapper-locations: classpath:mybatis/*.xml
    type-aliases-package: com.samay.game.entity