server:
    port: 8080

# log
logging:
    level:
        root: info

# management endpoints shutdown

# netty
netty:
    websocket:
        port: 8888
        ip: 172.16.58.88
        max-frame-size: 10240
        path: /ws

# rabbitmq
spring:
    application:
        name: rabbitmq-spring-boot
    rabbitmq:
        host: localhost
        port: 7777
        username: samay
        password: samay

